# Generated by Django 5.1.6 on 2025-02-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessorModule',
            new_name='Professor_to_Module',
        ),
    ]
